### PR TITLE
fix(package): update to using `webhint`

### PR DESCRIPTION
**Pull request by alrra**
@chrisguttandin The `sonarwhal` project has been renamed to `webhint`

Ref: https://medium.com/webhint/webhint-a-hinting-engine-for-the-web-ef0d3fa32ea9

Fix #430
Fix #431
Fix #432
Fix #433
Fix #434
Fix #435
Fix #436
Fix #437
Fix #438
Fix #439
Fix #440
Fix #441
Fix #442
Fix #443
Fix #444
Fix #445
Fix #446
Fix #447
Fix #448
Fix #449
Fix #450
Fix #451
Fix #452
Fix #453
Fix #454
Fix #455
Fix #456
Fix #457
Fix #458

### CODE REVIEW

**Comment by alrra** [comment]
Friendly ping @chrisguttandin 👋🏻

**Comment by chrisguttandin** [comment]
@alrra Can you please allow me to make changes to this pull request? I for example need to rename the .sonarwhalrc file.

**Comment by alrra** [comment]
> Can you please allow me to make changes to this pull request?

@chrisguttandin [That should already be the case](https://user-images.githubusercontent.com/1223565/44528500-9767b580-a69e-11e8-90da-b6ad2717cbbf.png).

> I for example need to rename the .sonarwhalrc file.

Done! Sorry I missed that when I did the PR.

**Comment by chrisguttandin** [comment]
Nevermind. I mistakenly cloned your fork and then tried to merge the pull request which of course had to fail. :-) Thanks again for these pull requests.

**Pull request merged**
